/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup KittenAssets;
extern const Sifteo::PinnedAssetImage Idle;
extern const Sifteo::PinnedAssetImage Jump;
extern const Sifteo::PinnedAssetImage Scared;
extern Sifteo::AssetGroup KittenAssets2;
extern const Sifteo::PinnedAssetImage Annoyed;
extern const Sifteo::PinnedAssetImage Playful;
extern const Sifteo::PinnedAssetImage Stretch;
extern const Sifteo::AssetTracker Music;
